---
# Install any required prerequisite packages
- name: Ensure presence of nettools, ssh, etc [apt]
  apt:
    name:
      - 'net-tools'
      - 'ethtool'
      - 'tcpdump'
      - 'psmisc' # for killall
      - 'lighttpd'
      - 'iperf'
      - 'httperf'
      #- 'nttcp'
      - 'ntp'
      - 'openssh-server'
      - 'build-essential'
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: Ensure presence of nettools, ssh, etc [pkg]
  pkgng:
    name:
      #- 'net-tools'
      #- 'ethtool'
      - 'tcpdump'
      - 'lighttpd'
      - 'iperf'
      - 'httperf'
      #- 'nttcp'
      - 'gtar'
    state: present
  when: ansible_pkg_mgr == 'pkgng'

- name: Check for nttcp
  command: which nttcp
  register: nttcp_present
  ignore_errors: true
  changed_when: False

- name: Install nttcp
  include: build_nttcp.yml
  when: nttcp_present.rc != 0

- name: Ensure SSH server is enabled and running
  service:
   name: "{{ teacup_ssh_service }}"
   enabled: yes
   state: started
  #when: ansible_service_mgr == 'systemd'
